[phases.setup]
nixPkgs = ["python3", "ffmpeg", "pip"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip --break-system-packages",
  "python3 -m pip install yt-dlp --break-system-packages",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

